name: maven-dependencies

 

on:
  workflow_dispatch:

 

jobs:
  build:
    runs-on: ubuntu-latest

 

    env:
      JAVA_HOME_17_X64: '/opt/hostedtoolcache/Java_Microsoft_jdk/17.0.3/x64'

 

    steps:
      - name: repo
        uses: actions/checkout@v2
      - name: Cache Java and Maven
        id: cache-java-maven
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.JAVA_HOME_17_X64 }}
            ~/.m2/repository
          key: java-maven-${{ runner.os }}-${{ hashFiles('**/*.yml') }}
          restore-keys: java-maven-

 

      - name: Install Java
        if: ${{ steps.cache-java-maven.outputs.cache-hit != 'true' }}
        id: install-java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

 

      - name: Check default Java version
        run: java -version

 

      - name: Set installed/cached Java path
        run: echo "JAVA_HOME=${{ env.JAVA_HOME_17_X64 }}/.." >> $GITHUB_ENV

 

      - name: Check installed/cached Java version
        run: |
          java -version

 

      - name: Build with Maven
        run: mvn clean package

 

      - name: Cache Maven artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: maven-artifacts-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}


